<?php
//HAHA, FIRST OF ALL , INTRODUCTION
/*
 * SCRIPT WRITTEN BY JEMPTON FOR CAREER LED BACKEND
 * ONLY PROGRAMMERS WITH PHP SERVER SCRIPTING KNOWLEDGE SHOULD EDIT THIS
 * OTHERWISE, CONTACT THE WRITER
 * OMONZEJELE PRECIOUS
 * COPYRIGHT
   */
  
	
	require("_processors/_functions.php");
	
	
  
?>